name: Comment on CI results
description: Comment on CI results
inputs:
  PULL_REQUEST_NUMBER:
    description: Pull request id
    required: false
    default: "0"
  COMMENT_BODY:
    description: Text of the comment
    required: true
runs:
  using: "composite"
  steps:  
    - name: Find Comment
      uses: peter-evans/find-comment@1769778a0c5bd330272d749d12c036d65e70d39d # v2.0.0
      id: fc
      with:
        issue-number: '${{ inputs.PULL_REQUEST_NUMBER }}'
        body-includes: 'runs/${{ github.run_id }}'

    - name: Update Comment
      uses: peter-evans/create-or-update-comment@c9fcb64660bc90ec1cc535646af190c992007c32 # v2.0.0
      with:
        issue-number: '${{ inputs.PULL_REQUEST_NUMBER }}'
        body: '${{ inputs.COMMENT_BODY }}'
        comment-id: ${{ steps.fc.outputs.comment-id }}
        edit-mode: replace
