name: NextJs bundle analysis
description: NextJs bundle analysis
inputs:
  PULL_REQUEST_NUMBER:
    description: Pull request id in case it does not exist in the context by default
    required: false
    default: "0"
runs:
  using: "composite"
  steps:  
    - name: Download PR bundle stats
      if: github.event.workflow_run.id
      uses: dawidd6/action-download-artifact@575b1e4167df67acf7e692af784566618b23c71e # v2.17.0
      with:
        workflow: build-fork.yml
        run_id: ${{ github.event.workflow_run.id }}
        workflow_conclusion: success
        name: nextjs
        path: .next

    - name: Analyze bundle
      shell: sh
      run: npx -p nextjs-bundle-analysis report

    - name: Upload bundle
      if: github.event_name == 'push'
      uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535 # v3.0.0
      with:
        name: bundle
        path: .next/analyze/__bundle_analysis.json

    - name: Download base branch bundle stats
      uses: dawidd6/action-download-artifact@575b1e4167df67acf7e692af784566618b23c71e # v2.17.0
      if: github.event_name != 'push'
      with:
        workflow: build-test-deploy.yml
        branch: main
        name: bundle
        path: .next/analyze/base/bundle/

    - name: Compare with base branch bundle
      if: github.event_name != 'push'
      shell: sh
      run: ls -laR .next/analyze/base && npx -p nextjs-bundle-analysis compare

    - name: Get comment body
      id: get-comment-body
      if: github.event_name != 'push'
      shell: bash
      run: |
        body=$(cat .next/analyze/__bundle_analysis_comment.txt)
        body="${body//'%'/'%25'}"
        body="${body//$'\n'/'%0A'}"
        body="${body//$'\r'/'%0D'}"
        echo ::set-output name=body::$body

    - name: Find Comment
      uses: peter-evans/find-comment@1769778a0c5bd330272d749d12c036d65e70d39d # v2.0.0
      if: github.event_name != 'push'
      id: fc
      with:
        issue-number: ${{ inputs.PULL_REQUEST_NUMBER }}
        body-includes: '<!-- __NEXTJS_BUNDLE -->'

    - name: Create Comment
      uses: peter-evans/create-or-update-comment@c9fcb64660bc90ec1cc535646af190c992007c32 # v2.0.0
      if: github.event_name != 'push' && steps.fc.outputs.comment-id == 0
      with:
        issue-number: ${{ inputs.PULL_REQUEST_NUMBER }}
        body: ${{ steps.get-comment-body.outputs.body }}

    - name: Update Comment
      uses: peter-evans/create-or-update-comment@c9fcb64660bc90ec1cc535646af190c992007c32 # v2.0.0
      if: github.event_name != 'push' && steps.fc.outputs.comment-id != 0
      with:
        issue-number: ${{ inputs.PULL_REQUEST_NUMBER }}
        body: ${{ steps.get-comment-body.outputs.body }}
        comment-id: ${{ steps.fc.outputs.comment-id }}
        edit-mode: replace
