name: Sync new issue to Height
description: Creates a new subtask in Height and moves it into the Github Issues Intake task on the interface project board

on:
  issues:
    types: [opened, reopened]

jobs:
  createHeightTask:
    runs-on: ubuntu-latest
    steps:
      - id: createHeightTaskRequest
        name: Create a new task with issue details in Height
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://api.height.app/tasks'
          method: 'POST'
          customHeaders: '{ "Content-Type": "application/json", "Authorization": "api-key ${{ secrets.HEIGHT_SECRET_TOKEN }}" }'
          data: '{
            "name": "${{ github.event.issue.title }}",
            "description": "${{ github.event.issue.description }}",
            "listIds": [
            "0540b3b8-bd44-4904-a97f-fd9d8780ef0a"
            ],
            "parentTaskId": "2dded224-8da0-4407-868f-d9cd018cbe52",
            "status": "backLog",
            "orderIntent": {
            "intent": "end"
            },
            "assigneesIds": [
            "848a5626-451f-4e15-b711-bd0a84883718",
            "fe99c0a6-ad7b-458d-ae9f-687af57e0053",
            "b0093618-6032-4e90-aa01-1dfc6628832d"
            ],
            "links": [],
            "fields": [
            {
            "fieldTemplateId": "f1bae626-c18c-4198-b354-560d1610766c",
            "name": "Tags",
            "type": "labels",
            "value": null,
            "label": null,
            "values": null,
            "date": null,
            "recursion": null,
            "labels": [
            {
            "id": "a7ba7d3e-d1d6-4111-92e6-e89c9456ea13",
            "model": "fieldLabel",
            "value": "github-issue",
            "date": null,
            "hue": 49,
            "deleted": false,
            "archived": false
            }
            ],
            "linkedTasks": null,
            "linkedTimer": null,
            "selectValue": null
            }
            ]
            }'
