name: Pin to ipfs cluster and nodes
description: Upload build to ipfs node
inputs:
  BUILD_PATH:
    description: path to the build directory
    required: true
  DOMAIN:
    description: Domain to unpin
    required: true
  IPFS_PRIMARY_SERVER_PORT:
    description: ''
    required: true
  IPFS_SECONDARY_SERVER_PORT:
    description: ''
    required: true
  IPFS_PRIMARY_SERVER:
    description: ''
    required: true
  IPFS_SECONDARY_SERVER:
    description: ''
    required: true
  IPFS_PRIMARY_SERVER_KEY:
    description: ''
    required: true
  IPFS_SECONDARY_SERVER_KEY:
    description: ''
    required: true
  IPFS_TERTIARY_SERVER_PORT:
    description: ''
    required: true
  IPFS_TERTIARY_SERVER:
    description: ''
    required: true
  IPFS_TERTIARY_KEY:
    description: ''
    required: true

runs:
  using: 'composite'
  steps:
    - name: Prepare env and Compress build on IPFS servers
      id: ipfs-prepare
      continue-on-error: false
      shell: bash
      run: |
        echo -n "${{ inputs.IPFS_PRIMARY_SERVER_KEY }}" | base64 -d >> ./p_key
        echo -n "${{ inputs.IPFS_SECONDARY_SERVER_KEY }}" | base64 -d >> ./s_key
        echo -n "${{ inputs.IPFS_TERTIARY_KEY }}" | base64 -d >> ./key
        chmod 400 ./p_key ./s_key ./key

    - name: Upload build to IPFS Primary Server
      id: ipfs-scp-primary
      continue-on-error: false
      shell: bash
      run: |
        tar -czf './${{ inputs.BUILD_PATH }}' | ssh -o StrictHostKeyChecking=no \
        -p \${{ inputs.IPFS_PRIMARY_SERVER_PORT }} \
        -i ./p_key ipfs@\${{ inputs.IPFS_PRIMARY_SERVER }} "tar -zxf - -C ./${{ inputs.BUILD_PATH }}/"
        ssh -o StrictHostKeyChecking=no \
        -p \${{ inputs.IPFS_PRIMARY_SERVER_PORT }} \
        -i ./p_key ipfs@\${{ inputs.IPFS_PRIMARY_SERVER }} "ipfs add -r ./${{ inputs.BUILD_PATH }}/" > /tmp/hash
        IPFS_HASH="$(cat /tmp/hash | awk '{print $2}')"
        ssh -o StrictHostKeyChecking=no \
        -p \${{ inputs.IPFS_PRIMARY_SERVER_PORT }} \
        -i ./p_key ipfs@\${{ inputs.IPFS_PRIMARY_SERVER_PORT }} "ipfs pin add $IPFS_HASH "

    - name: Upload build to IPFS Secondary Server
      id: ipfs-scp-secondary
      continue-on-error: false
      shell: bash
      run: |
        tar -czf './${{ inputs.BUILD_PATH }}' | ssh -o StrictHostKeyChecking=no \
        -p \${{ inputs.IPFS_SECONDARY_SERVER_PORT }} \
        -i ./s_key ipfs@\${{ inputs.IPFS_SECONDARY_SERVER }} "tar -zxf - -C ./${{ inputs.BUILD_PATH }}/"
        ssh -o StrictHostKeyChecking=no \
        -p \${{ inputs.IPFS_SECONDARY_SERVER_PORT }} \
        -i ./s_key ipfs@\${{ inputs.IPFS_SECONDARY_SERVER }} "ipfs add -r ./${{ inputs.BUILD_PATH }}/"
        IPFS_HASH="$(cat /tmp/hash | awk '{print $2}')"
        ssh -o StrictHostKeyChecking=no \
        -p \${{ inputs.IPFS_SECONDARY_SERVER_PORT }} \
        -i ./s_key ipfs@\${{ inputs.IPFS_SECONDARY_SERVER_PORT }} "ipfs pin add $IPFS_HASH "

    - name: Upload build to IPFS Tertiary Server
      id: ipfs-scp-tertiary
      continue-on-error: false
      shell: bash
      run: |
        tar -czf './${{ inputs.BUILD_PATH }}' | ssh -o StrictHostKeyChecking=no \
        -p \${{ inputs.IPFS_TERTIARY_SERVER_PORT }} \
        -i ./key ipfs@\${{ inputs.IPFS_TERTIARY_SERVER }} "tar -zxf - -C ./${{ inputs.BUILD_PATH }}/"
        ssh -o StrictHostKeyChecking=no \
        -p \${{ inputs.IPFS_TERTIARY_SERVER_PORT }} \
        -i ./key ipfs@\${{ inputs.IPFS_TERTIARY_SERVER }} "ipfs add -r ./${{ inputs.BUILD_PATH }}/"
        IPFS_HASH="$(ssh -o StrictHostKeyChecking=no \
        -p \${{ inputs.IPFS_TERTIARY_SERVER_PORT }} \
        -i ./key ipfs@\${{ inputs.IPFS_TERTIARY_SERVER }} "ipfs add -r ./${{ inputs.BUILD_PATH }}/ | awk '{print $2}' ")"
        ssh -o StrictHostKeyChecking=no \
        -p \${{ inputs.IPFS_TERTIARY_SERVER_PORT }} \
        -i ./key ipfs@\${{ inputs.IPFS_TERTIARY_SERVER_PORT }} "ipfs pin add $IPFS_HASH "

    - name: Clean build and tmp directory on Servers
      continue-on-error: false
      id: ipfs-clean
      shell: bash
      run: |
        ssh -o StrictHostKeyChecking=no \
        -p \${{ inputs.IPFS_IPFS_PRIMARY_SERVER_PORT }} \
        -i ./p_key ipfs@\${{ inputs.IPFS_PRIMARY_SERVER }} "rm -rf ./${{ inputs.BUILD_PATH }}/"
        ssh -o StrictHostKeyChecking=no \
        -p \${{ inputs.IPFS_SECONDARY_SERVER_PORT }} \
        -i ./s_key ipfs@\${{ inputs.IPFS_SECONDARY_SERVER }} "rm -rf ./${{ inputs.BUILD_PATH }}/"
        ssh -o StrictHostKeyChecking=no \
        -p \${{ inputs.IPFS_TERTIARY_SERVER_PORT }} \
        -i ./key ipfs@\${{ inputs.IPFS_TERTIARY_SERVER }} "rm -rf ./${{ inputs.BUILD_PATH }}/"
        rm -rf ./p_* ./s_* ./ke*
