export enum QueryKeys {
    USE_POWERS = 'USE_POWERS',
    VOTE_ON_PROPOSAL = 'VOTE_ON_PROPOSAL',
    VOTING_POWER_AT = 'VOTING_POWER_AT',
    GOVERNANCE_TOKENS = 'GOVERNANCE_TOKENS',
    POOL_TOKENS = 'POOL_TOKENS',
    GENERAL_STAKE_UI_DATA = 'GENERAL_STAKE_UI_DATA',
    USER_STAKE_UI_DATA = 'USER_STAKE_UI_DATA',
    TRANSACTION_HISTORY = 'TRANSACTION_HISTORY'
}

export const POOLING_INTERVAL = 60000;