export const enum QueryKeys {
  USE_POWERS = 'USE_POWERS',
  VOTE_ON_PROPOSAL = 'VOTE_ON_PROPOSAL',
  VOTING_POWER_AT = 'VOTING_POWER_AT',
  GOVERNANCE_TOKENS = 'GOVERNANCE_TOKENS',
  TRANSACTION_HISTORY = 'TRANSACTION_HISTORY',
  POOL_TOKENS = 'POOL_TOKENS',
  GENERAL_STAKE_UI_DATA = 'GENERAL_STAKE_UI_DATA',
  USER_STAKE_UI_DATA = 'USER_STAKE_UI_DATA',
  APPROVED_AMOUNT = 'APPROVED_AMOUNT',
  POOL_APPROVED_AMOUNT = 'POOL_APPROVED_AMOUNT',
}

export const POLLING_INTERVAL = 60000;
