export enum QueryKeys {
  USE_POWERS = 'USE_POWERS',
  VOTE_ON_PROPOSAL = 'VOTE_ON_PROPOSAL',
  VOTING_POWER_AT = 'VOTING_POWER_AT',
  GOVERNANCE_TOKENS = 'GOVERNANCE_TOKENS',
  POOL_TOKENS = 'POOL_TOKENS',
  GENERAL_STAKE_UI_DATA = 'GENERAL_STAKE_UI_DATA',
  USER_STAKE_UI_DATA = 'USER_STAKE_UI_DATA',
  RESERVE_INCENTIVE_DATA = 'RESERVE_INCENTIVE_DATA',
  USER_INCENTIVE_DATA = 'USER_INCENTIVE_DATA',
  POOL_RESERVES = 'POOL_RESERVES',
  USER_POOL_RESERVES = 'USER_POOL_RESERVES',
}

export const POOLING_INTERVAL = 60000;
