name: Add label to PR with CI results
description: Add label to PR with CI results
inputs:
  SUCCESS:
    description: Text of the comment
    required: true
  PULL_REQUEST_NUMBER:
    description: Pull request id
    required: false
    default: "0"
runs:
  using: "composite"
  steps:
    - name: delete success label
      uses: actions-ecosystem/action-remove-labels@v1
      with:
          labels: "CI run has succeded!"
          number: ${{ inputs.PULL_REQUEST_NUMBER }}
    - name: delete fail label
      uses: actions-ecosystem/action-remove-labels@v1
      with:
          labels: "CI run has failed!"
          number: ${{ inputs.PULL_REQUEST_NUMBER }}
    - name: adding success label
      uses: actions-ecosystem/action-add-labels@v1
      if: ${{ inputs.SUCCESS == 'true' }}
      with:
          labels: "CI run has succeded!"
          number: ${{ inputs.PULL_REQUEST_NUMBER }}
    - name: adding fail label
      uses: actions-ecosystem/action-add-labels@v1
      if: ${{ inputs.SUCCESS == 'false' }}
      with:
          labels: "CI run has failed!"
          number: ${{ inputs.PULL_REQUEST_NUMBER }}
