name: Build app and static
description: Build nextjs app and export static files
inputs:
  CYPRESS_TENDERLY_ACCOUNT:
    description: tenderly account name
    required: true
  CYPRESS_TENDERLY_KEY:
    description: tenderly secret key
    required: true
  CYPRESS_TENDERLY_PROJECT:
    description: tenderly porject name
    required: true
  YARN_TEST_COMMAND:
    description: yarn command to run test
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4.0.2
      with:
        node-version-file: '.nvmrc'
        cache: 'yarn'

    - name: install
      shell: sh
      run: |
        yarn --frozen-lockfile --prefer-offline
        yarn add serve

    - name: download build
      if: github.event_name != 'workflow_run'
      uses: actions/download-artifact@v4.1.4
      with:
        name: out
        path: out

    - name: Download static build
      if: github.event_name == 'workflow_run'
      uses: dawidd6/action-download-artifact@ea71f332a90fd52416b1629b933dcf7e0ccd421d # v2.22.0
      with:
        workflow: build-fork.yml
        run_id: ${{ github.event.workflow_run.id }}
        workflow_conclusion: success
        name: out
        path: out

    - name: test
      uses: cypress-io/github-action@v6.6.1
      with:
        headless: true
        install: false
        record: false
        start: yarn serve:static
        wait-on: 'http://localhost:3000'
        command: ${{ inputs.YARN_TEST_COMMAND }}
      env:
        CYPRESS_URL: 'http://localhost:3000'
        CYPRESS_TENDERLY_ACCOUNT: ${{ inputs.CYPRESS_TENDERLY_ACCOUNT }}
        CYPRESS_TENDERLY_KEY: ${{ inputs.CYPRESS_TENDERLY_KEY }}
        CYPRESS_TENDERLY_PROJECT: ${{ inputs.CYPRESS_TENDERLY_PROJECT }}

    - name: upload screenshots
      uses: actions/upload-artifact@v4.3.1
      if: failure()
      with:
        name: cypress-fail-screenshots-${{ github.job }}-${{ matrix.market }}
        path: cypress/screenshots
