name: Build app and static
description: Build nextjs app and export static files
inputs:
  CYPRESS_TENDERLY_ACCOUNT:
    description: tenderly account name
    required: true
  CYPRESS_TENDERLY_KEY:
    description: tenderly secret key
    required: true
  CYPRESS_TENDERLY_PROJECT:
    description: tenderly porject name
    required: true
  YARN_TEST_COMMAND:
    description: yarn command to run test
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # v3.4.1
      with:
        node-version-file: '.nvmrc'
        cache: 'yarn'

    - name: install
      shell: sh
      run: |
        yarn --frozen-lockfile --prefer-offline
        yarn add serve

    - name: download build
      if: github.event_name != 'workflow_run'
      uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741 # v3.0.0
      with:
        name: out
        path: out

    - name: Download static build
      if: github.event_name == 'workflow_run'
      uses: dawidd6/action-download-artifact@ea71f332a90fd52416b1629b933dcf7e0ccd421d # v2.22.0
      with:
        workflow: build-fork.yml
        run_id: ${{ github.event.workflow_run.id }}
        workflow_conclusion: success
        name: out
        path: out

    - name: test
      uses: cypress-io/github-action@16aacf8ea6a67e5e5d907d34bc3be8ad0e6e979f # v3.0.3
      with:
        headless: true
        install: false
        record: false
        start: yarn serve:static --no-request-logging
        wait-on: 'http://localhost:3000'
        command: ${{ inputs.YARN_TEST_COMMAND }}
      env:
        CYPRESS_URL: 'http://localhost:3000'
        CYPRESS_TENDERLY_ACCOUNT: ${{ inputs.CYPRESS_TENDERLY_ACCOUNT }}
        CYPRESS_TENDERLY_KEY: ${{ inputs.CYPRESS_TENDERLY_KEY }}
        CYPRESS_TENDERLY_PROJECT: ${{ inputs.CYPRESS_TENDERLY_PROJECT }}

    - name: upload screenshots
      uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535 # v3.0.0
      if: failure()
      with:
        name: cypress-fail-screenshots-${{ github.job }}-${{ matrix.market }}
        path: cypress/screenshots

    - name: upload video
      uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535 # v3.0.0
      if: failure()
      with:
        name: cypress-fail-videos-${{ github.job }}-${{ matrix.market }}
        path: cypress/videos
