name: Build app and static
description: Build nextjs app and export static files
inputs:
  BUILD_ARTIFACT_NAME:
    description: optional name of the static build artifact
    required: false
    default: out
  PR_INFO:
    description: should this artifact be uploaded
    required: false
    default: 'true'
  NEXTJS_BUILD:
    description: should this artifact be uploaded
    required: false
    default: 'true'
runs:
  using: 'composite'
  steps:
    - name: Save PR number
      if: github.event.number && inputs.PR_INFO == 'true'
      shell: sh
      run: |
        mkdir -p ./__pr
        echo ${{ github.event.number }} > ./__pr/NUM
    - name: store PR info
      if: github.event.number && inputs.PR_INFO == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: pr
        path: __pr/
        retention-days: 10
        overwrite: true
    - name: store static build
      uses: actions/upload-artifact@v4
      with:
        name: '${{ inputs.BUILD_ARTIFACT_NAME }}'
        path: out/
        retention-days: 10
        overwrite: true
    - name: store nextjs build
      if: inputs.NEXTJS_BUILD == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: 'nextjs_${{ github.job }}'
        path: |
          .next
          !.next/cache
        retention-days: 10
        overwrite: true
        include-hidden-files: true
