const MANEKI_LEVERAGER_V2_ABI = [
  {
    inputs: [
      { internalType: 'address', name: '_poolAddressesProvider', type: 'address' },
      { internalType: 'address', name: '_glpToken', type: 'address' },
      { internalType: 'address', name: '_weth', type: 'address' },
      { internalType: 'address', name: '_gmxRewardRouter', type: 'address' },
      { internalType: 'address', name: '_protocolDataProvider', type: 'address' },
      { internalType: 'address', name: '_pool', type: 'address' },
      { internalType: 'address', name: '_protocolOracle', type: 'address' },
    ],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'address', name: 'user', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'leverage', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'glpPosition', type: 'uint256' },
    ],
    name: 'LeveragedGlpPosition',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'previousOwner', type: 'address' },
      { indexed: true, internalType: 'address', name: 'newOwner', type: 'address' },
    ],
    name: 'OwnershipTransferred',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: 'address', name: 'account', type: 'address' }],
    name: 'Paused',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'address', name: 'borrowAsset', type: 'address' },
      { indexed: false, internalType: 'bool', name: 'validity', type: 'bool' },
    ],
    name: 'SetValidBorrowAssets',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'address', name: 'collateral', type: 'address' },
      { indexed: false, internalType: 'bool', name: 'validity', type: 'bool' },
    ],
    name: 'SetValidCollateral',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: 'address', name: 'account', type: 'address' }],
    name: 'Unpaused',
    type: 'event',
  },
  { stateMutability: 'payable', type: 'fallback' },
  {
    inputs: [],
    name: 'ADDRESSES_PROVIDER',
    outputs: [{ internalType: 'contract IPoolAddressesProvider', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'POOL',
    outputs: [{ internalType: 'contract IPool', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'acceptedBorrowAssets',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'acceptedCollateral',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_leverage', type: 'uint256' }],
    name: 'calculateApr',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_collateral', type: 'address' },
      { internalType: 'uint256', name: '_amount', type: 'uint256' },
      { internalType: 'address[]', name: '_borrowTokens', type: 'address[]' },
      { internalType: 'uint256[]', name: '_ratio', type: 'uint256[]' },
      { internalType: 'uint256', name: '_leverage', type: 'uint256' },
    ],
    name: 'calculateFlashLoanTokens',
    outputs: [
      { internalType: 'address[]', name: 'borrowTokens', type: 'address[]' },
      { internalType: 'uint256[]', name: 'amount', type: 'uint256[]' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address[]', name: 'assets', type: 'address[]' },
      { internalType: 'uint256[]', name: 'amounts', type: 'uint256[]' },
      { internalType: 'uint256[]', name: 'premiums', type: 'uint256[]' },
      { internalType: 'address', name: 'initiator', type: 'address' },
      { internalType: 'bytes', name: 'params', type: 'bytes' },
    ],
    name: 'executeOperation',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'feeGlp',
    outputs: [{ internalType: 'contract IRewardTracker', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'glpAToken',
    outputs: [{ internalType: 'contract IGlpRewardsAToken', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'glpManager',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'glpToken',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'gmxRewardRouter',
    outputs: [{ internalType: 'contract IGmxRewardRoter', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_collateral', type: 'address' },
      { internalType: 'uint256', name: '_amount', type: 'uint256' },
      { internalType: 'address[]', name: '_borrowTokens', type: 'address[]' },
      { internalType: 'uint256[]', name: '_ratio', type: 'uint256[]' },
      { internalType: 'uint256', name: '_leverage', type: 'uint256' },
    ],
    name: 'leverageGlp',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'paused',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'pool',
    outputs: [{ internalType: 'contract IPool', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'profitRatio',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'protocolDataProvider',
    outputs: [{ internalType: 'contract IProtocolDataProvider', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'protocolOracle',
    outputs: [{ internalType: 'contract IProtocolOracle', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'renounceOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_profitRatio', type: 'uint256' }],
    name: 'setProfitRatio',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address[]', name: '_borrowAssets', type: 'address[]' },
      { internalType: 'bool[]', name: '_boolArray', type: 'bool[]' },
    ],
    name: 'setValidBorrowAssets',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address[]', name: '_collaterals', type: 'address[]' },
      { internalType: 'bool[]', name: '_boolArray', type: 'bool[]' },
    ],
    name: 'setValidCollateral',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'stakedFeeGlp',
    outputs: [{ internalType: 'contract IRewardTracker', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'weth',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  { stateMutability: 'payable', type: 'receive' },
];

export default MANEKI_LEVERAGER_V2_ABI;
