name: Test adding label to pr

concurrency:
  group: ${{ github.workflow }}-${{ github.event.workflow_run.id }}
  cancel-in-progress: true

on:
  workflow_run:
    workflows: ["Build PR From Fork"]
    types: ["completed"]
    branches-ignore: ["main"]

jobs:
  notify_failure:
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ needs.prepare_jobs.outputs.pr_number }}
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v3.0.0
      - name: Get PR number
        shell: sh
        run: |
          echo "${{ env.PR_NUMBER }}"
      - name: Label
        uses: ./.github/actions/fork-result-label
        continue-on-error: true
        with:
          SUCCESS: 'false'
          PULL_REQUEST_NUMBER: 8

  notify_success:
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ needs.prepare_jobs.outputs.pr_number }}
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v3.0.0
      - name: Get PR number
        shell: sh
        run: |
          echo "${{ env.PR_NUMBER }}"
      - name: Label
        uses: ./.github/actions/fork-result-label
        continue-on-error: true
        with:
          SUCCESS: 'true'
          PULL_REQUEST_NUMBER: 7
