name: Build and deploy to IPFS

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: restore
        continue-on-error: true
        id: restore
        uses: actions/download-artifact@v2
        with:
          path: out
          name: out_${{github.sha}}

      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: install
        run: yarn --frozen-lockfile

      - name: build
        if: steps.restore.outcome != 'success'
        run: yarn build:static
        env:
          ENABLE_TESTNET: true

      - name: pinata
        id: pinata
        uses: aave/pinata-action@v1.1
        with:
          PINATA_API_KEY: ${{ secrets.PINATA_API_KEY }}
          PINATA_SECRET_KEY: ${{ secrets.PINATA_SECRET_KEY }}
          PIN_ALIAS: "${{ format('pull_request_{0}', github.head_ref) }}"
          BUILD_LOCATION: './out'
          CID_VERSION: 1

      # - name: crust
      #   uses: crustio/ipfs-crust-action@18f5ab4e8496351cfaca10a55ced7119cb0fe677
      #   continue-on-error: true
      #   timeout-minutes: 2
      #   with:
      #     cid: ${{ steps.pinata.outputs.hash }}
      #     seeds: ${{ secrets.CRUST_SEEDS }}

      - name: Deploy master
        id: deploy
        if: |
          github.event_name == 'push' &&
          github.ref == 'refs/heads/master'
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
          HASH: ${{ steps.pinata.outputs.hash }}
          CF_DEPLOYMENT_DOMAIN: v3-internal-test.aave.com
        run: |
          yarn add axios
          node scripts/update-cloudflare.js
